### PR TITLE
Conan Center setup

### PR DESCRIPTION
**Pull request by sourcedelica**
This is work related to getting CAF onto Conan Center, which is part of [#515](https://github.com/actor-framework/actor-framework/issues/515) in the main `actor-framework` project.

The CI configuration is complete but it's not yet building successfully on [Travis](https://travis-ci.org/sourcedelica/conan-caf).  This branch is WIP until it is passing CI across all of the required Conan platforms (see the "CI Integration" section of the [Conan Center doc page](http://conanio.readthedocs.io/en/latest/packaging/bintray/conan_center_guide.html)).

The CI configuration on this branch is using my personal Bintray account for testing.  Once CI is passing I'll set up the CAF organization Bintray account and make the request to have it included in Conan Center, then update the Conan config to point to that.

### CODE REVIEW

**Comment by sourcedelica** [comment]
The Linux jobs are failing when running `conan test_package`, at the very end when it builds a test executable.  This build runs ok with my own Linux VM using the same commands.  For GCC, the errors [are](https://travis-ci.org/sourcedelica/conan-caf/jobs/276934134):

```
lib/libcaf_io_static.a(basp_broker.cpp.o): In function `operator()':
/libcaf_io/src/basp_broker.cpp:312: undefined reference to `caf::skip_t::operator std::function<caf::result<caf::message> (caf::scheduled_actor*, caf::message_view&)>() const'
```
Does that ring a bell?

The [clang](https://travis-ci.org/sourcedelica/conan-caf/jobs/276934136) builds have a ton of undefined symbols.  I've never tested conan-caf using clang on Linux but I do on Mac all the time and the builds on Travis Mac also have a ton of undefined symbols.

I will investigate further.  I need to figure out how to use the Conan multi-build infrastructure locally so I can try to replicate issue.

**Comment by sourcedelica** [comment]
I was able to replicate the GCC link error.

**Comment by sourcedelica** [comment]
I've tested everything except Visual Studio using the Conan multi-build tool.  Hopefully Travis agrees with me.  Visual Studio is next.

**Comment by Neverlord** [comment]
Great seeing your progress. Thanks for all your work on this!

**Comment by sourcedelica** [comment]
No problem!  

@neverlord, question for you: we need to be able to specify the following from Conan:

- Standard library including ABI flavor (`libstdc++` old, `libstdc++` new, `libc++`)
- Architecture (`x86`, `x86_64`)

Currently for GCC (and Clang except in the case where `libc++` is selected) CAF compiles with `libstdc++` with the default C++11 ABI, which in most cases is the `new` ABI (or `-D_GLIBCXX_USE_CXX11_ABI=1`).

For example, on my VM, it will use the `new` ABI to compile CAF:

    $ g++ --version -v 2>&1 | grep -- --with-default-libstdcxx-abi
    ...   --with-default-libstdcxx-abi=new  ...

When building a C++ package with Conan you need to tag the package with the standard library that it used to compile the package, including in this case the old/new ABI flavor.  

Similarly CAF builds using the default architecture (usually `x86_64`) but the Conan needs the package to be tagged with the architecture used.   For both the stdlib and the architecture I want to be able to force specific settings, overriding the defaults.

I can submit a PR in the main project to add support to `CMakeLists.txt` for these.  Let me know what you think.

**Comment by sourcedelica** [comment]
First build with all Unix-based builds passing: https://travis-ci.org/sourcedelica/conan-caf/builds/278027526

I'm going to do Windows next then work on the TODO items.

**Comment by sourcedelica** [comment]
VS 2015 is [passing](https://ci.appveyor.com/project/sourcedelica/conan-caf/build/1.0.14).

I've commented out the VS 2017 build from the Appveyor config for now due to a compile error (see [#596](https://github.com/actor-framework/actor-framework/issues/596))

The next step is getting the official Bintray repository setup:

- [x] Create Bintray organization and [repository](https://bintray.com/actor-framework/actor-framework)
- [x] Switch Travis / Appveyor configs to push packages the new Bintray repository
- [ ] Merge this branch to `actor-framework/conan:master`
- [ ] Enable Travis / Appveyor builds for `actor-framework/conan:master` (@Neverlord)
- [ ] Submit repository for inclusion in Conan Center
- [ ] Transfer ownership of organization to Dominik

@Neverlord, when you get a chance please create a user on Bintray and let me know what your username is.  I will add you to the organization.   Also, please enable Travis and Appveyor builds for `actor-framework/conan:master`.

**Comment by sourcedelica** [comment]
There is another new issue [#597](https://github.com/actor-framework/actor-framework/issues/597) to add a few features to the CAF build configuration.  I'm hoping that they will not need to be done before approval for inclusion into Conan Center but it's possible that one or two of them will be required.

**Comment by sourcedelica** [comment]
I am creating a new squashed PR for merge

**Pull request closed without merging**
